### ISSUE TITLE
Submit as next.js example

### ISSUE THREAD

**Issue by sorin-davidoi** [ooade/next-react-toolbox#2]
You might want to add this to the [`examples`](https://github.com/zeit/next.js/tree/master/examples) directory of next.js. Would fit in nicely, especially since MaterialUI, SemanticUI and react-md are already there.

**Comment by ooade** [comment]
Yeah, definitely. We just need to do one or two things like #4 before doing that. Thanks for raising that up :+1:

**Comment by ooade** [comment]
@sorin-davidoi Closing this in favor of https://github.com/zeit/next.js/tree/v3-beta/examples/with-react-toolbox
